default:
  patient:
    name: Biggie
    age: 18
    dob: "XXXX-XX-XX"
    doe: "2025-01-01"
  data:
    input_dir: data-raw
    output_dir: data
    format: all
  processing:
    use_duckdb: yes
    parallel: yes
    verbose: yes
    age_group: ""
  output:
    generate_qmd: yes
    generate_plots: yes
    generate_tables: yes
  report:
    template: template.qmd
    format: neurotyp-pediatric-typst
    output_dir: output
  # mcp:
  #   pdf_path: "data/raw/pdf/wisc5.pdf"
  #   tree_path: "results/wisc5_report_structure.json"
  #   llm_base_url: "http://localhost:11434/v1"
  #   llm_model: "ollama/llama3.1"
  #   lookup_table: "~/Dropbox/neuropsych_lookup_table.csv"
