#!/usr/bin/env Rscript

# TEMPLATE CHECKER (FIXED)
# This script checks for required template files ONLY (not domain files)
# Domain files should be generated by 03_generate_domain_files.R based on available data

# Function to print colored messages
.print_colored <- function(message, color = "blue") {
  colors <- list(
    red = "\033[0;31m",
    green = "\033[0;32m",
    yellow = "\033[1;33m",
    blue = "\033[0;34m",
    reset = "\033[0m"
  )

  cat(paste0(colors[[color]], message, colors$reset, "\n"))
}

.print_colored("🔍 CHECKING REQUIRED TEMPLATE FILES", "blue")
.print_colored("=====================================", "blue")
.print_colored("")

# Define the template directory.
# `voice/` lives as a sibling of the cingulate package (e.g. luria/voice/),
# not inside it. cingulate::voice_dir() resolves that location at runtime
# and honors the LURIA_VOICE_DIR env var as an override.
template_dir <- cingulate::voice_dir("style", "templates", "typst-report")

# Check if the template directory exists
if (!dir.exists(template_dir)) {
  .print_colored(paste("Template directory not found:", template_dir), "red")
  stop("Template directory not found")
}

# List all files in the template directory
template_files <- list.files(template_dir, full.names = TRUE)
.print_colored(
  paste("Found", length(template_files), "files in template directory"),
  "blue"
)

# Define essential template files (EXCLUDING domain files)
essential_files <- c(
  "_00-00_tests.qmd",
  "_01-00_nse.qmd",
  "_01-01_behav_obs.qmd",
  "_03-00_sirf_text.qmd",
  "_03-00_sirf.qmd",
  "_03-00_dsm5_icd10_dx.qmd",
  "_03-01_recs.qmd",
  "_03-02_signature.qmd",
  "_03-03_appendix.qmd",
  "_03-03a_informed_consent.qmd",
  "_03-03b_examiner_qualifications.qmd",
  "_quarto.yml",
  "_variables.yml",
  "config.yml",
  "template.qmd"
)

# Check each essential file
missing_files <- character()
for (file in essential_files) {
  source_file <- file.path(template_dir, file)

  if (!file.exists(file)) {
    if (file.exists(source_file)) {
      .print_colored(
        paste("Copying", file, "from template directory..."),
        "yellow"
      )
      file.copy(source_file, file)
      if (file.exists(file)) {
        .print_colored(paste("✓ Successfully copied", file), "green")
      } else {
        .print_colored(paste("✗ Failed to copy", file), "red")
        missing_files <- c(missing_files, file)
      }
    } else {
      .print_colored(paste("✗ Source file not found:", source_file), "red")
      missing_files <- c(missing_files, file)
    }
  } else {
    .print_colored(paste("✓ File already exists:", file), "green")
  }
}

# Ensure neurotyp Quarto extensions are available
extensions_source_dir <- here::here(
  "inst",
  "quarto",
  "_extensions",
  "brainworkup"
)
extensions_target_dir <- here::here("_extensions", "brainworkup")

if (!dir.exists(extensions_source_dir)) {
  .print_colored(
    paste("Extension source directory not found:", extensions_source_dir),
    "red"
  )
  missing_files <- c(
    missing_files,
    file.path(extensions_source_dir, "neurotyp-.*")
  )
} else {
  if (!dir.exists(extensions_target_dir)) {
    dir.create(extensions_target_dir, recursive = TRUE, showWarnings = FALSE)
    .print_colored(
      paste("Created extension target directory:", extensions_target_dir),
      "yellow"
    )
  }

  neurotyp_dirs <- list.dirs(
    extensions_source_dir,
    recursive = FALSE,
    full.names = FALSE
  )
  neurotyp_dirs <- neurotyp_dirs[grepl("^neurotyp-", neurotyp_dirs)]

  if (length(neurotyp_dirs) == 0) {
    .print_colored(
      paste(
        "No neurotyp-* extensions found under",
        extensions_source_dir,
        "to copy."
      ),
      "red"
    )
    missing_files <- c(
      missing_files,
      file.path(extensions_target_dir, "neurotyp-.*")
    )
  } else {
    for (ext_dir in neurotyp_dirs) {
      source_dir <- file.path(extensions_source_dir, ext_dir)
      dest_dir <- file.path(extensions_target_dir, ext_dir)

      if (dir.exists(dest_dir)) {
        .print_colored(paste("✓ Extension already exists:", dest_dir), "green")
      } else if (file.exists(dest_dir) && !dir.exists(dest_dir)) {
        .print_colored(
          paste(
            "✗ A non-directory item blocks",
            dest_dir,
            "- please resolve manually."
          ),
          "red"
        )
        missing_files <- c(missing_files, dest_dir)
      } else {
        .print_colored(
          paste("Copying", ext_dir, "extension from template directory..."),
          "yellow"
        )
        # file.copy requires the destination to be an existing directory when copying
        # folders; copy into the target root so the extension folder is created there.
        success <- file.copy(
          source_dir,
          extensions_target_dir,
          recursive = TRUE
        )
        if (isTRUE(all(success)) && dir.exists(dest_dir)) {
          .print_colored(paste("✓ Successfully copied", dest_dir), "green")
        } else {
          .print_colored(paste("✗ Failed to copy", ext_dir, "extension"), "red")
          missing_files <- c(missing_files, dest_dir)
        }
      }
    }
  }
}

# DO NOT create domain files here - they should be created by 03_generate_domain_files.R
.print_colored(
  "\n📝 Note: Domain files (_02-*.qmd) should be generated by:",
  "yellow"
)
.print_colored("   Rscript 03_generate_domain_files.R", "yellow")
.print_colored("   based on available data, not from templates.", "yellow")

# Final check
if (length(missing_files) > 0) {
  .print_colored("\nSome essential files are still missing:", "red")
  for (file in missing_files) {
    .print_colored(paste("  -", file), "red")
  }
  .print_colored(
    "Please create these files manually before running the workflow",
    "red"
  )
  quit(status = 1)
} else {
  .print_colored("\n✅ All essential template files are in place", "green")
  .print_colored(
    "Next step: Run 'Rscript 02_data_processor_module.R' to create data files",
    "green"
  )
  quit(status = 0)
}
